# Generated by Django 6.0 on 2026-01-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="date",
        ),
    ]
