# Generated by Django 6.0 on 2026-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["username"]},
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="truck",
            options={"ordering": ["condition"]},
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="money",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
