# Generated by Django 6.0 on 2026-01-12 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0002_remove_service_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(default="serivce description", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(default="service name", max_length=63),
            preserve_default=False,
        ),
    ]
