# Generated by Django 6.0 on 2026-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0002_alter_driver_options_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="money",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
