# Generated by Django 6.0 on 2026-01-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0003_service_date_service_description_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
