# Generated by Django 6.0 on 2026-01-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0004_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
